name: 'Banksiaview Professional Services '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25952
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#040404'
    - '#333333'
    - '#b0b0b0'
    - '#31abe6'
  brandStrength: 1
  lightness: 0.3125
  saturation: 1
  rhythmicContrast: 1
purpose: []
