name: Banksiaview Professional Services Pty Ltd
favicon: null
layout_spectrum: 0.6620067765470594
typography_spectrum: 0.9966820774134248
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.20683347946032882
  lightness: 0.47114218957722187
  saturation: 0.5375037877820432
  rhythmicContrast: 0.08955195150338113
purpose: []
